import type { Metadata } from 'next';
import { siteName } from '@/lib/config';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: `The terms that govern your use of ${siteName}.`,
};

const UPDATED = 'June 11, 2026';

export default function TermsPage() {
  return (
    <main className="container">
      <h1>Terms of Service</h1>
      <p className="muted">Last updated: {UPDATED}</p>

      <p>
        These terms govern your use of the {siteName} app and website. By
        creating an account or using the service you agree to them.
      </p>

      <h2>What {siteName} is</h2>
      <p>
        {siteName} is a marketplace that connects homeowners with independent
        renovation contractors. Contractors are not our employees or agents. We
        do not perform renovation work, and a contractor&rsquo;s appearance in
        the app — including the &ldquo;Verified&rdquo; badge, which reflects an
        identity and licensing check at a point in time — is not a guarantee of
        their work. Contracts for renovation work are between you and the
        contractor.
      </p>

      <h2>AI estimates</h2>
      <p>
        Photo-based cost estimates are generated by AI and are informational
        ranges, not quotes, bids, or appraisals. Actual costs are set by the
        contractor you hire.
      </p>

      <h2>Payments, deposits, and fees</h2>
      <ul>
        <li>
          Payments are processed by Stripe. When you accept a quote and pay the
          in-app deposit, the deposit goes to the contractor and {siteName}{' '}
          charges a platform commission, shown before you pay.
        </li>
        <li>
          Deposits may be held in milestone escrow and released per the schedule
          shown in the app. Refunds of a deposit are full and can be issued by
          the contractor or by us.
        </li>
        <li>
          Contractors may purchase an optional Pro subscription. Sponsored
          placement is always labeled and never changes organic search ranking.
        </li>
      </ul>

      <h2>Your account</h2>
      <p>
        You must be 18 or older and provide accurate information. You are
        responsible for activity under your account. You can delete your
        account anytime in the app (Profile → Delete account).
      </p>

      <h2>Acceptable use</h2>
      <p>
        Don&rsquo;t misuse the service: no unlawful activity, harassment,
        scraping, circumventing fees by moving agreed in-app payments
        off-platform, fake reviews, or attempts to access other users&rsquo;
        data. We may suspend or terminate accounts that violate these terms.
      </p>

      <h2>Disclaimers and liability</h2>
      <p>
        The service is provided &ldquo;as is.&rdquo; To the maximum extent
        permitted by law, {siteName} disclaims implied warranties and is not
        liable for disputes between homeowners and contractors, for the quality
        of renovation work, or for indirect or consequential damages. Our total
        liability for any claim is limited to the platform fees you paid us in
        the twelve months before the claim.
      </p>

      <h2>Disputes</h2>
      <p>
        We encourage you to contact us first — most issues are resolved
        directly. These terms are governed by the laws of the State of
        California, and disputes will be resolved in the state or federal
        courts of San Francisco County, California.
      </p>

      <h2>Changes and contact</h2>
      <p>
        We may update these terms; material changes will be posted here with a
        new date above. Questions:{' '}
        <a href="mailto:support@renovateconnect.app">
          support@renovateconnect.app
        </a>
        .
      </p>
    </main>
  );
}
